/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static java.lang.Thread.sleep;
import javax.swing.JOptionPane;
import java.util.Random;

/**
 *
 * @author Matheus
 */
public class telaGame extends javax.swing.JFrame {
    String resp;
    int apostaMin = 1, contador = 1, placarAnte = 1, cont;
    equipes gru1;
    equipes gru2;
    equipes gru3;
    equipes gru4;
    equipes gru5;
    /**
     * Creates new form telaGame
     */
    public telaGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rodada = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        numRodada = new javax.swing.JLabel();
        placar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        firstGroup = new javax.swing.JLabel();
        secondGroup = new javax.swing.JLabel();
        thirdGroup = new javax.swing.JLabel();
        fourthGroup = new javax.swing.JLabel();
        quintoGroup = new javax.swing.JLabel();
        setG1 = new javax.swing.JButton();
        setG2 = new javax.swing.JButton();
        setG3 = new javax.swing.JButton();
        setG4 = new javax.swing.JButton();
        setG5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        firstScore = new javax.swing.JLabel();
        secondScore = new javax.swing.JLabel();
        thirdScore = new javax.swing.JLabel();
        fourthScore = new javax.swing.JLabel();
        quintoScore = new javax.swing.JLabel();
        iniciarRodada = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        daVez = new javax.swing.JTextField();
        desafiado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        aposta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        formEquipes = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        g2 = new javax.swing.JRadioButton();
        g5 = new javax.swing.JRadioButton();
        g4 = new javax.swing.JRadioButton();
        g3 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        group1 = new javax.swing.JTextField();
        group2 = new javax.swing.JTextField();
        group3 = new javax.swing.JTextField();
        group4 = new javax.swing.JTextField();
        group5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        buttonVoltar = new javax.swing.JButton();
        buttonContinuar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Passa ou Reprova");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rodada.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 102)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Rodada");

        numRodada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        numRodada.setText("1");

        javax.swing.GroupLayout rodadaLayout = new javax.swing.GroupLayout(rodada);
        rodada.setLayout(rodadaLayout);
        rodadaLayout.setHorizontalGroup(
            rodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rodadaLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(numRodada)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        rodadaLayout.setVerticalGroup(
            rodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rodadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numRodada))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(rodada, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 25, -1, -1));

        placar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 153)));
        placar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Placar");
        placar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        firstGroup.setText("Grupo1");

        secondGroup.setText("Grupo2");

        thirdGroup.setText("Grupo3");

        fourthGroup.setText("Grupo4");

        quintoGroup.setText("Grupo5");

        setG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setG1ActionPerformed(evt);
            }
        });

        setG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setG2ActionPerformed(evt);
            }
        });

        setG3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setG3ActionPerformed(evt);
            }
        });

        setG4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setG4ActionPerformed(evt);
            }
        });

        setG5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setG5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(secondGroup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setG2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(thirdGroup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setG3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(fourthGroup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setG4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(quintoGroup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setG5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(firstGroup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setG1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(firstGroup)
                            .addComponent(setG1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secondGroup)
                            .addComponent(setG2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thirdGroup))
                    .addComponent(setG3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fourthGroup)
                    .addComponent(setG4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(quintoGroup)
                    .addComponent(setG5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        placar.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 110));

        firstScore.setText("0");

        secondScore.setText("0");

        thirdScore.setText("0");

        fourthScore.setText("0");

        quintoScore.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstScore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondScore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thirdScore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourthScore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quintoScore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thirdScore, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fourthScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quintoScore)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        placar.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 30, 110));

        jPanel1.add(placar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 160, 160));

        jButton1.setText("INICIAR RODADA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("REGRAS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Grupo da vez");

        jLabel3.setText("Grupo desafiado");

        aposta.setEditable(false);
        aposta.setText("1");

        jLabel5.setText("Aposta");

        jButton3.setText("VOLTAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("DADO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout iniciarRodadaLayout = new javax.swing.GroupLayout(iniciarRodada);
        iniciarRodada.setLayout(iniciarRodadaLayout);
        iniciarRodadaLayout.setHorizontalGroup(
            iniciarRodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iniciarRodadaLayout.createSequentialGroup()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(iniciarRodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(iniciarRodadaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(iniciarRodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton2))))
                .addGap(167, 167, 167))
            .addGroup(iniciarRodadaLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(iniciarRodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(iniciarRodadaLayout.createSequentialGroup()
                        .addComponent(daVez, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(desafiado, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(iniciarRodadaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(87, 87, 87))))
            .addGroup(iniciarRodadaLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(iniciarRodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aposta)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        iniciarRodadaLayout.setVerticalGroup(
            iniciarRodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iniciarRodadaLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(iniciarRodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(iniciarRodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daVez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desafiado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(iniciarRodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jPanel1.add(iniciarRodada, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 450, 390));

        formEquipes.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 102)));
        formEquipes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formEquipesFocusLost(evt);
            }
        });
        formEquipes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(g2);
        g2.setText("2 grupos");
        g2.setActionCommand("2g");
        g2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(g5);
        g5.setSelected(true);
        g5.setText("5 grupos");
        g5.setActionCommand("5g");
        g5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(g4);
        g4.setText("4 grupos");
        g4.setActionCommand("4g");
        g4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(g3);
        g3.setText("3 grupos");
        g3.setActionCommand("3g");
        g3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g3ActionPerformed(evt);
            }
        });

        jLabel11.setText("Quantidade de grupos");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(g2)
                    .addComponent(g5)
                    .addComponent(g4)
                    .addComponent(g3))
                .addGap(28, 28, 28))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(g2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(g3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(g4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(g5)
                .addContainerGap())
        );

        g2.getAccessibleContext().setAccessibleDescription("");
        g5.getAccessibleContext().setAccessibleDescription("");
        g4.getAccessibleContext().setAccessibleDescription("");
        g3.getAccessibleContext().setAccessibleDescription("");

        formEquipes.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 35, -1, -1));
        formEquipes.add(group1, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 84, 130, -1));
        formEquipes.add(group2, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 115, 130, -1));
        formEquipes.add(group3, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 146, 130, -1));
        formEquipes.add(group4, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 177, 130, -1));
        formEquipes.add(group5, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 208, 130, -1));

        jLabel13.setText("Nomes");
        formEquipes.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 64, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Forme as equipes");
        formEquipes.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 12, -1, -1));

        buttonVoltar.setText("VOLTAR");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });
        formEquipes.add(buttonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 251, -1, -1));

        buttonContinuar.setText("CONTINUAR");
        buttonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContinuarActionPerformed(evt);
            }
        });
        formEquipes.add(buttonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 251, -1, -1));

        jPanel1.add(formEquipes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 320, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void g4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g4ActionPerformed
        // TODO add your handling code here:
        group1.setVisible(true);
        group2.setVisible(true);
        group3.setVisible(true);
        group4.setVisible(true);
        group5.setVisible(false);
        group5.setText("");
    }//GEN-LAST:event_g4ActionPerformed

    private void g2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g2ActionPerformed
        // TODO add your handling code here:
        group1.setVisible(true);
        group2.setVisible(true);
        group3.setVisible(false);
        group4.setVisible(false);
        group5.setVisible(false);
        group3.setText("");
        group4.setText("");
        group5.setText(""); 
       
    }//GEN-LAST:event_g2ActionPerformed

    private void g3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g3ActionPerformed
        // TODO add your handling code here:
        group1.setVisible(true);
        group2.setVisible(true);
        group3.setVisible(true);
        group4.setVisible(false);
        group5.setVisible(false);
        group4.setText("");
        group5.setText("");
    }//GEN-LAST:event_g3ActionPerformed

    private void g5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g5ActionPerformed
        // TODO add your handling code here:
        group1.setVisible(true);
        group2.setVisible(true);
        group3.setVisible(true);
        group4.setVisible(true);
        group5.setVisible(true);
    }//GEN-LAST:event_g5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        rodada.setVisible(false);
        placar.setVisible(false);
        iniciarRodada.setVisible(false);
        aposta.setText(""+apostaMin);
    }//GEN-LAST:event_formWindowOpened

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        // TODO add your handling code here:
        new telaInicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void buttonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonContinuarActionPerformed
        // TODO add your handling code here:
        gru1 = new equipes(group1.getText());
        gru2 = new equipes(group2.getText());
        gru3 = new equipes(group3.getText());
        gru4 = new equipes(group4.getText());
        gru5 = new equipes(group5.getText());
        switch (buttonGroup1.getSelection().getActionCommand()) {
            case "2g":
                firstGroup.setText(gru1.getNome());
                secondGroup.setText(gru2.getNome());
                thirdGroup.setVisible(false);
                thirdScore.setVisible(false);
                fourthGroup.setVisible(false);
                fourthScore.setVisible(false);
                quintoGroup.setVisible(false);
                quintoScore.setVisible(false);
                setG3.setVisible(false);
                setG4.setVisible(false);
                setG5.setVisible(false);
                firstScore.setText(""+gru1.getPontos());
                secondScore.setText(""+gru2.getPontos());
                cont = 2;
                gru3.setNome("null");
                gru4.setNome("null");
                gru5.setNome("null");
                break;
            case "3g":
                firstGroup.setText(gru1.getNome());
                secondGroup.setText(gru2.getNome());
                thirdGroup.setText(gru3.getNome());
                fourthGroup.setVisible(false);
                fourthScore.setVisible(false);
                quintoGroup.setVisible(false);
                quintoScore.setVisible(false);
                setG4.setVisible(false);
                setG5.setVisible(false);
                firstScore.setText(""+gru1.getPontos());
                secondScore.setText(""+gru2.getPontos());
                thirdScore.setText(""+gru3.getPontos());
                cont = 3;
                gru4.setNome("null");
                gru5.setNome("null");
                break;
            case "4g":
                firstGroup.setText(gru1.getNome());
                secondGroup.setText(gru2.getNome());
                thirdGroup.setText(gru3.getNome());
                fourthGroup.setText(gru4.getNome());
                quintoGroup.setVisible(false);
                quintoScore.setVisible(false);
                setG5.setVisible(false);
                firstScore.setText(""+gru1.getPontos());
                secondScore.setText(""+gru2.getPontos());
                thirdScore.setText(""+gru3.getPontos());
                fourthScore.setText(""+gru4.getPontos());
                cont = 4;
                gru5.setNome("null");
                break;
            case "5g":
                cont = 5;
                int pontos[] = new int[cont];
                firstGroup.setText(gru1.getNome());
                secondGroup.setText(gru2.getNome());
                thirdGroup.setText(gru3.getNome());
                fourthGroup.setText(gru4.getNome());
                quintoGroup.setText(gru5.getNome());
                firstScore.setText(""+gru1.getPontos());
                secondScore.setText(""+gru2.getPontos());
                thirdScore.setText(""+gru3.getPontos());
                fourthScore.setText(""+gru4.getPontos());
                quintoScore.setText(""+gru5.getPontos());
                
                break;
            default:
                throw new AssertionError();
        }
            rodada.setVisible(true);
            placar.setVisible(true);
            iniciarRodada.setVisible(true);
            formEquipes.setVisible(false);
    }//GEN-LAST:event_buttonContinuarActionPerformed

    private void formEquipesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formEquipesFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_formEquipesFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(aposta.getText()) < apostaMin || aposta.getText().equals("")){
            aposta.setText(""+apostaMin);
        }
        if (validarEq(daVez.getText()) && validarEq(desafiado.getText())){
            disputa();
            mudarLayout();
        }else{
            JOptionPane.showMessageDialog(this, "Nome do time invalido!");
        }
        //youkosojitsuryuku   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new regras().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new telaInicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int r = new Random().nextInt(5) + 1;
        JOptionPane.showMessageDialog(this, r);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void setG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setG1ActionPerformed
        // TODO add your handling code here:
        desafiado.setText(firstGroup.getText());
    }//GEN-LAST:event_setG1ActionPerformed

    private void setG2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setG2ActionPerformed
        // TODO add your handling code here:
        desafiado.setText(secondGroup.getText());
    }//GEN-LAST:event_setG2ActionPerformed

    private void setG3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setG3ActionPerformed
        // TODO add your handling code here:
        desafiado.setText(thirdGroup.getText());        
    }//GEN-LAST:event_setG3ActionPerformed

    private void setG4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setG4ActionPerformed
        // TODO add your handling code here:
        desafiado.setText(fourthGroup.getText());
    }//GEN-LAST:event_setG4ActionPerformed

    private void setG5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setG5ActionPerformed
        // TODO add your handling code here:
        desafiado.setText(quintoGroup.getText());
    }//GEN-LAST:event_setG5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aposta;
    private javax.swing.JButton buttonContinuar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JTextField daVez;
    private javax.swing.JTextField desafiado;
    private javax.swing.JLabel firstGroup;
    private javax.swing.JLabel firstScore;
    private javax.swing.JPanel formEquipes;
    private javax.swing.JLabel fourthGroup;
    private javax.swing.JLabel fourthScore;
    private javax.swing.JRadioButton g2;
    private javax.swing.JRadioButton g3;
    private javax.swing.JRadioButton g4;
    private javax.swing.JRadioButton g5;
    private javax.swing.JTextField group1;
    private javax.swing.JTextField group2;
    private javax.swing.JTextField group3;
    private javax.swing.JTextField group4;
    private javax.swing.JTextField group5;
    private javax.swing.JPanel iniciarRodada;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel numRodada;
    private javax.swing.JPanel placar;
    private javax.swing.JLabel quintoGroup;
    private javax.swing.JLabel quintoScore;
    private javax.swing.JPanel rodada;
    private javax.swing.JLabel secondGroup;
    private javax.swing.JLabel secondScore;
    private javax.swing.JButton setG1;
    private javax.swing.JButton setG2;
    private javax.swing.JButton setG3;
    private javax.swing.JButton setG4;
    private javax.swing.JButton setG5;
    private javax.swing.JLabel thirdGroup;
    private javax.swing.JLabel thirdScore;
    // End of variables declaration//GEN-END:variables
    void disputa(){
        char h;
        int pontos = Integer.parseInt(aposta.getText());
        equipes p1 = checkParticipants(daVez.getText());
        equipes p2 = checkParticipants(desafiado.getText());
        JOptionPane.showMessageDialog(this, "Preparar!");
        try {
            sleep(2000);
        } catch (Exception e) {
        }
        resp = JOptionPane.showInputDialog(this, "GO");
        h = resp.charAt(0);
        if (h == 'q' || h == 'w'|| h == 'a'|| h == 's'|| h == 'z'|| h == 'x') {
            JOptionPane.showMessageDialog(this, daVez.getText()+" ganhou");
            resp = JOptionPane.showInputDialog("Acertou? (s/n)");
            if (resp.equals("n")){
                resp = JOptionPane.showInputDialog(desafiado.getText()+" acertou? (s/n)");
                if (resp.equals("n")){
                    p1.setPontos(calcPontos(p1, 'l', pontos));
                    p2.setPontos(calcPontos(p2, 'l', pontos));
                }else{
                    p1.setPontos(calcPontos(p1, 'l', pontos));
                    p2.setPontos(calcPontos(p2, 'w', pontos));
                }
            }else{
                p1.setPontos(calcPontos(p1, 'w', pontos));
                p2.setPontos(calcPontos(p2, 'l', pontos));
            }
        } else 
        if (h == '2' || h == '3'|| h == '5'|| h == '6'|| h == '8'|| h == '9'){
            JOptionPane.showMessageDialog(this, desafiado.getText()+" ganhou");
            resp = JOptionPane.showInputDialog("Acertou? (s/n)");
            if (resp.equals("n")){
                resp = JOptionPane.showInputDialog(daVez.getText()+" acertou? (s/n)");
                if (resp.equals("n")){
                    p1.setPontos(calcPontos(p1, 'l', pontos));
                    p2.setPontos(calcPontos(p2, 'l', pontos));
                }else{
                    p1.setPontos(calcPontos(p1, 'w', pontos));
                    p2.setPontos(calcPontos(p2, 'l', pontos));
                }
            }else{
                p1.setPontos(calcPontos(p1, 'l', pontos));
                p2.setPontos(calcPontos(p2, 'w', pontos));
            }    
        }else{
            JOptionPane.showMessageDialog(this, "INVÁLIDO");
            disputa();
        }
    }
    equipes checkParticipants(String part){
        if (gru1.getNome().equals(part)){
            return gru1;
        }else
        if (gru2.getNome().equals(part)){
           return gru2; 
        }else
        if (gru3.getNome().equals(part)){
            return gru3;
        }else
        if (gru4.getNome().equals(part)){
            return gru4;
        }else        
            return gru5;       
        }
    boolean validarEq(String part){
        if (gru1.getNome().equals(part)){
            return true;
        }else
        if (gru2.getNome().equals(part)){
           return true; 
        }else
        if (gru3.getNome().equals(part)){
            return true;
        }else
        if (gru4.getNome().equals(part)){
            return true;
        }else 
        if(gru5.getNome().equals(part)){
            return true;
        }else
            return false;
    }
    int calcPontos(equipes eq, char w, int pontos){
        if (w == 'l'){
            if ((eq.getPontos() - pontos) <= 0){
                cont -= 1;
                if (cont == 1){
                    JOptionPane.showMessageDialog(this, "Temos um vencedor!");
                }
            }
            return eq.getPontos() - pontos;
        }else{
            return eq.getPontos() + pontos + 1;
        }
    }
    void mudarLayout(){
        int placar = Integer.parseInt(numRodada.getText());
        if (contador == cont){
            numRodada.setText(""+(placar + 1));
            if (((placar+1) == 3|| (placar+1) == 5 || (placar+1) == 15) && checkTrocarPlacar(placar)){
            apostaMin += 1;
        }
        if ((placar + 1) > 1){
            aposta.setEditable(true);
            }
            contador = 1;
        }else{
            contador += 1;
        }
        /*
        firstScore.setText(""+checkParticipants(daVez.getText()).getPontos());
        secondScore.setText(""+checkParticipants(desafiado.getText()).getPontos());
        */
       // ordenarPlacar(,);
        firstScore.setText(""+gru1.getPontos());
        secondScore.setText(""+gru2.getPontos());
        thirdScore.setText(""+gru3.getPontos());
        fourthScore.setText(""+gru4.getPontos());
        quintoScore.setText(""+gru5.getPontos());
        daVez.setText("");
        desafiado.setText("");
        aposta.setText(""+apostaMin);
    }
    /**
    void ordenarPlacar(int [] gPontos, String []gNome , int quant){
        //pegar quantas equipes tem pelo parametro, inserir no vetor  e ordenar, talvez retornar o vetor
        int aux;
        String tmp;
        for (int i = 0; i < gPontos.length; i++){
            for(int y = i+1; y < i; y++){
                if(gPontos[y] > gPontos[i]){
                    aux = gPontos[y];
                    tmp = gNome[y];
                    gPontos[y] = gPontos[i];
                    gNome[y] = gNome[i];
                    gPontos[i] = aux;
                    gNome[i] = tmp;
                }
            }
        }
        firstScore.setText(""+gru1.getPontos());
        secondScore.setText(""+gru2.getPontos());
        thirdScore.setText(""+gru3.getPontos());
        fourthScore.setText(""+gru4.getPontos());
        quintoScore.setText(""+gru5.getPontos());
        Corrigir o aumento de aposta minima toda vez que ele sobe
        gru1.getPontos();
        gru2.getPontos();
        gru3.getPontos();
        gru4.getPontos();
        gru5.getPontos();
    }*/
    boolean checkTrocarPlacar(int placarAtual){
        //se o placar anterior for igual ao atual, não muda, se for diferente muda,se for diferente retorna true e muda o placar anterior ´para o atual
        //variavel global para guardar a anterior
        if (placarAnte != placarAtual){
            placarAnte = placarAtual;
            return true;
        }else
            return false;
    }
}